#!/bin/bash

red='\033[0;31m'
lightGreen='\033[1;32m'
noColor='\033[0m'

for (( i=0; i <= 100; i++ ))
do
	inFile=in$i
	outFile=out$i

	if [ -f $inFile ]; then
		printf "Running Test-case $i : \n"
		printf "Input : "
		cat $inFile
		printf "\n"
		./$1 < $inFile > o
		printf "Your Output : "
		cat o
		printf "\n"
		printf "Correct Output : "
		cat $outFile
		printf "\n"

		diff -w $outFile o >/dev/null;REPLY=$?
		if [ ${REPLY} -eq 0 ]
		then
			if [ ! -z $2 ] 
			then 
				printf "Exact matching : ${lightGreen}PASS${noColor}\n"
			else
				printf "Exact matching : PASS\n"
			fi
		else
			if [ ! -z $2 ] 
			then 
				printf "Exact matching : ${red}FAIL${noColor}\n"
			else
				printf "Exact matching : FAIL\n"
			fi
		fi
		printf "======================================\n"
	fi
done